<!DOCTYPE html>
<html xmlns="https://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.353">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R for Geographic Science - Descriptive Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R for Geographic Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" rel="" target="" aria-current="page">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Intro.html" rel="" target="">
 <span class="menu-text">Overview</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./Installing.html" rel="" target="">
 <span class="menu-text">Installing R</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./RstudioInt.qmd" rel="" target="">
 <span class="menu-text">RStudio Interface</span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./Descriptive_Statistics.html">Descriptive Statistics</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R coding manual</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Overview</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Installing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Installing R</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RStudioInt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Understanding RStudio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./RCalculator.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using R as a calculator</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Descriptive_Statistics.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Descriptive Statistics</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Mapping_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Choropleth mapping</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Classical_Measures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Classical Measures</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-purpose-of-quantification" id="toc-the-purpose-of-quantification" class="nav-link active" data-scroll-target="#the-purpose-of-quantification"><span class="header-section-number">1</span> The purpose of quantification</a></li>
  <li><a href="#sec-GDF" id="toc-sec-GDF" class="nav-link" data-scroll-target="#sec-GDF"><span class="header-section-number">2</span> Geographic Data Frames (GDF)</a></li>
  <li><a href="#numerical-summaries" id="toc-numerical-summaries" class="nav-link" data-scroll-target="#numerical-summaries"><span class="header-section-number">3</span> Numerical Summaries</a>
  <ul class="collapse">
  <li><a href="#minimum-and-maximum-values" id="toc-minimum-and-maximum-values" class="nav-link" data-scroll-target="#minimum-and-maximum-values"><span class="header-section-number">3.1</span> Minimum and Maximum values</a></li>
  <li><a href="#the-arithmetic-mean" id="toc-the-arithmetic-mean" class="nav-link" data-scroll-target="#the-arithmetic-mean"><span class="header-section-number">3.2</span> The arithmetic mean</a></li>
  <li><a href="#the-weighted-mean" id="toc-the-weighted-mean" class="nav-link" data-scroll-target="#the-weighted-mean"><span class="header-section-number">3.3</span> The weighted mean</a></li>
  <li><a href="#the-mode" id="toc-the-mode" class="nav-link" data-scroll-target="#the-mode"><span class="header-section-number">3.4</span> The mode</a></li>
  </ul></li>
  <li><a href="#visual-summaries" id="toc-visual-summaries" class="nav-link" data-scroll-target="#visual-summaries"><span class="header-section-number">4</span> Visual summaries</a>
  <ul class="collapse">
  <li><a href="#creating-a-histogram-in-r" id="toc-creating-a-histogram-in-r" class="nav-link" data-scroll-target="#creating-a-histogram-in-r"><span class="header-section-number">4.1</span> Creating a Histogram in R</a></li>
  </ul></li>
  <li><a href="#box-and-whisker-plots" id="toc-box-and-whisker-plots" class="nav-link" data-scroll-target="#box-and-whisker-plots"><span class="header-section-number">5</span> Box-and-whisker plots</a>
  <ul class="collapse">
  <li><a href="#multiple-box-plots" id="toc-multiple-box-plots" class="nav-link" data-scroll-target="#multiple-box-plots"><span class="header-section-number">5.1</span> Multiple box-plots</a></li>
  </ul></li>
  <li><a href="#other-useful-visualisations" id="toc-other-useful-visualisations" class="nav-link" data-scroll-target="#other-useful-visualisations"><span class="header-section-number">6</span> Other useful visualisations</a>
  <ul class="collapse">
  <li><a href="#pie-charts" id="toc-pie-charts" class="nav-link" data-scroll-target="#pie-charts"><span class="header-section-number">6.1</span> Pie charts</a></li>
  <li><a href="#bar-plots" id="toc-bar-plots" class="nav-link" data-scroll-target="#bar-plots"><span class="header-section-number">6.2</span> Bar plots</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Descriptive Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>In the previous section, using R as a Calculator, introduced summary statistics in R. The outputs of the <code>summary(...)</code> function in R provides readily useful data insights including the:</p>
<ul>
<li>Minimum value</li>
<li>Maximum value</li>
<li>Average value (arithmetic mean)</li>
<li>Median value (middle)</li>
</ul>
<p>When dealing with numerical data, it also gives insights regarding quartile breaks.</p>
<p>The function behaves differently when processing non-numeric data, where it will return metrics concerning the frequency of occurrences, field length and <em>class</em>. For now, let’s focus on unpacking the numerical qualities.</p>
<section id="the-purpose-of-quantification" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="the-purpose-of-quantification"><span class="header-section-number">1</span> The purpose of quantification</h2>
<p>According to Richard Harris and Claire Jarvis, “data collection and analysis are central to the functioning of contemporary society…data handling of statistics is a necessary skill to social and scientific debate” <span class="citation" data-cites="harris2014statistics">(<a href="#ref-harris2014statistics" role="doc-biblioref">Harris and Jarvis 2014</a>)</span>. Once data has been gathered, the next task is to <em>make sense of it</em>. A simple example could be: having just finished asking 100 people what their favourite colour is, how would you know which colour is most popular?</p>
<p>Statistics is derived from the Latin word ‘Statisticum’ that translates to ‘of the government’ or ‘of the state’. Therefore, the study of statistics literally means the study of the state, or to analyse <em>something</em> to do with the state. In the simple example given above, the state is the 100 surveyed people. The mission becomes to analyse the 100 people.</p>
</section>
<section id="sec-GDF" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="sec-GDF"><span class="header-section-number">2</span> Geographic Data Frames (GDF)</h2>
<p>A data frame is a the next step up from a matrix. While a matrix contains a single class of data (i.e.&nbsp;purely numeric), a data frame can contain difference classes of data variable. An example of a data frame is noted below along with a test of the object’s class. The data shows the effect of vitamin C on the growth rate of teeth for the first 6 rows of 60 observations.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(<span class="at">x =</span> ToothGrowth, <span class="at">n =</span> <span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>    len supp dose
1   4.2   VC  0.5
2  11.5   VC  0.5
3   7.3   VC  0.5
4   5.8   VC  0.5
5   6.4   VC  0.5
6  10.0   VC  0.5
7  11.2   VC  0.5
8  11.2   VC  0.5
9   5.2   VC  0.5
10  7.0   VC  0.5</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(<span class="at">x =</span> ToothGrowth)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "data.frame"</code></pre>
</div>
</div>
<p>A geographic data frame differs from a conventional data frame as it includes geographic data such as geometries, longitude, and latitude. Geographic data fields, make it possible to spatialise and map your data.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Class in data objects
</div>
</div>
<div class="callout-body-container callout-body">
<p>Class is a shortened handle for classification. R is able to identify a range of different classes either via the <code>summary(...)</code> or <code>class(...)</code> functions. Knowing the class of your data will help you to select the most appropriate instruments for analysis.</p>
</div>
</div>
</section>
<section id="numerical-summaries" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="numerical-summaries"><span class="header-section-number">3</span> Numerical Summaries</h2>
<section id="minimum-and-maximum-values" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="minimum-and-maximum-values"><span class="header-section-number">3.1</span> Minimum and Maximum values</h3>
<p>The minimum (<span class="math inline">\(\wedge\)</span>) and maximum values (<span class="math inline">\(\vee\)</span>)are self-explanatory. They represent the lowest and highest value present in your data vector/variable. These can be found easily in R using the <code>min(...)</code> and <code>max(...)</code> functions. For example, using the <code>mtcars</code> data set, we can find the minimum horsepower (hp) for the featured 1970s cars using the following lines of code:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 52</code></pre>
</div>
</div>
<p>The maximum horsepower is quickly retrieved using the following:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(mtcars<span class="sc">$</span>hp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 335</code></pre>
</div>
</div>
</section>
<section id="the-arithmetic-mean" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="the-arithmetic-mean"><span class="header-section-number">3.2</span> The arithmetic mean</h3>
<p>As discussed in a section ‘R as a Calculator’, the arithmetic mean is an average. It’s equation is as follows:</p>
<p><span class="math display">\[
\bar{x} = \frac{\sum{x_i}}{n}
\]</span> Here, the <span class="math inline">\(\bar{x}\)</span> represents the calculated mean (average), the <span class="math inline">\(\sum\)</span> means the sum total of something, <span class="math inline">\(x_i\)</span> represents your numerical data vector/variable - a single index (<span class="math inline">\(i\)</span>), and <span class="math inline">\(n\)</span> is number of observations in your vector/variable. Therefore, the mean can be described as the sum total of a numerical string divided by its length.</p>
<p>To help illustrate this point, imagine you have a vector that is as follows: <code>1, 2, 3, 4, 5, 6</code>. Working out the mean can be achieved in the following way:</p>
<p><span class="math display">\[
\begin{align}
\bar{x} &amp; = \frac{1+2+3+4+5+6}{6}
\\
\\
&amp; = \frac{21}{6}
\\
\\
&amp; = 3.5
\end{align}
\]</span></p>
<p>The mean can be considered as a measure of centrality, a concept that will be expanded on in the next section. Otherwise, it is a useful tool in determining the average from a distribution of values. It is worth noting that the values do not need to be ordered. In R it is easily applied using the <code>mean(...)</code> function. For example:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.5</code></pre>
</div>
</div>
</section>
<section id="the-weighted-mean" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="the-weighted-mean"><span class="header-section-number">3.3</span> The weighted mean</h3>
<p>Sometimes, you’ll face situations where you are dealing with means across an array of columns. For example, your vector can comprise of values related to daily temperatures. The data is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating data</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>week_days <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Sunday"</span>, <span class="st">"Monday"</span>, <span class="st">"Tuesday"</span>, <span class="st">"Wednesday"</span>, <span class="st">"Thursday"</span>, <span class="st">"Friday"</span>, <span class="st">"Saturday"</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>daily_temp <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">19</span>, <span class="dv">19</span>, <span class="dv">20</span>, <span class="dv">19</span>, <span class="dv">21</span>, <span class="dv">20</span>, <span class="dv">20</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>Samp_temp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(week_days, daily_temp)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Renaming columns</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Samp_temp)[<span class="fu">names</span>(Samp_temp) <span class="sc">==</span> <span class="st">"week_days"</span>] <span class="ot">&lt;-</span> <span class="st">"Day"</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(Samp_temp)[<span class="fu">names</span>(Samp_temp) <span class="sc">==</span> <span class="st">"daily_temp"</span>] <span class="ot">&lt;-</span> <span class="st">"Temperature"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Plotting transposed (t) table</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">t</span>(Samp_temp))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 13%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Day</td>
<td style="text-align: left;">Sunday</td>
<td style="text-align: left;">Monday</td>
<td style="text-align: left;">Tuesday</td>
<td style="text-align: left;">Wednesday</td>
<td style="text-align: left;">Thursday</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">Saturday</td>
</tr>
<tr class="even">
<td style="text-align: left;">Temperature</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">21</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">20</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Because we’re cooped up indoors for the majority of the week, we might weight our opinions of weather of this week was ‘good’ or ‘bad’ based on the weekends. In this case, a weighted mean can be a helpful tool. It’s equation is as follows:</p>
<p><span class="math display">\[
\bar{x}_w = \frac{\sum_{i=1}^{n}(x_i \cdot w_i)}{\sum_{i=1}^{n}w_i} \ \ \ \ \therefore \ \ \ \ \bar{x}_w = \frac{\sum{wx}}{\sum{w}}
\]</span></p>
<p>Here, <span class="math inline">\(w\)</span> represents your weights; as before, <span class="math inline">\(x_i\)</span> are your indexed values. This formula may seem intimidating, however, all it is doing is allowing you to increase the importance of certain values over another by adjusting their multiplication factors. The arithmetic mean places equal weightings to observations so that the even weighting is <span class="math inline">\(\frac{1}{7} \approx 0.142\)</span> for each day of the week; tallied up, their value will be <span class="math inline">\(1\)</span>:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manually inputted original weightings (approximated)</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>Samp_temp<span class="sc">$</span>original_weight <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.142</span>, <span class="fl">0.142</span>, <span class="fl">0.142</span>, <span class="fl">0.142</span>, <span class="fl">0.142</span>, <span class="fl">0.142</span>, <span class="fl">0.142</span>)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Output table</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">t</span>(Samp_temp[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">3</span>)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Day</td>
<td style="text-align: left;">Sunday</td>
<td style="text-align: left;">Monday</td>
<td style="text-align: left;">Tuesday</td>
<td style="text-align: left;">Wednesday</td>
<td style="text-align: left;">Thursday</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">Saturday</td>
</tr>
<tr class="even">
<td style="text-align: left;">original_weight</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
<td style="text-align: left;">0.142</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>If we wanted to place emphasis on Saturday and Sunday, we’d override the weights with higher decimal values placed on these days - ensuring that the total still comes up to <span class="math inline">\(1\)</span>:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Manually inputted original weightings (approximated)</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>Samp_temp<span class="sc">$</span>adjusted_weight <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="fl">0.25</span>, <span class="fl">0.25</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Output table</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(<span class="fu">t</span>(Samp_temp[,<span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">4</span>)]))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 12%">
</colgroup>
<tbody>
<tr class="odd">
<td style="text-align: left;">Day</td>
<td style="text-align: left;">Sunday</td>
<td style="text-align: left;">Monday</td>
<td style="text-align: left;">Tuesday</td>
<td style="text-align: left;">Wednesday</td>
<td style="text-align: left;">Thursday</td>
<td style="text-align: left;">Friday</td>
<td style="text-align: left;">Saturday</td>
</tr>
<tr class="even">
<td style="text-align: left;">adjusted_weight</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.10</td>
<td style="text-align: left;">0.25</td>
<td style="text-align: left;">0.25</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With these values, it is possible to calculate the weighted mean using the equation above:</p>
<p><span class="math display">\[\begin{align}
\bar{x}_w &amp; = \frac{\sum{(1.9, 1.9, 2, 1.9, 2.1, 5, 5)}} {(0.1, 0.1, 0.1, 0.1, 0.1, 0.25, 0.25)}
\\
\\
&amp; = \frac{19.8 \ \cdot \ 1}{1}
\\
\\
&amp; = 19.8

\end{align}\]</span> \end{equation}</p>
<p>In R, the <code>weighted.mean(...)</code> function can be used calculate this value. Using our data frame <code>Samp_temp</code> the process is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">weighted.mean</span>(<span class="at">x =</span> Samp_temp<span class="sc">$</span>Temperature, <span class="at">w =</span> Samp_temp<span class="sc">$</span>adjusted_weight)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 19.8</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is possible to generate rows of weighted means based on column values. However, this process requires the use of R’s <code>apply(...)</code> function in order to evaluate the array. The approximate format is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>your_data<span class="sc">$</span>w_avg <span class="ot">&lt;-</span> <span class="fu">apply</span>(<span class="at">X =</span> your_data,</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>                         <span class="at">MARGIN =</span> <span class="dv">1</span>, </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">FUN =</span> <span class="cf">function</span>(x) <span class="fu">weighted.mean</span>(<span class="at">x =</span> x[<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(your_data), <span class="at">w =</span> adjusted_column_weights))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="description" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="description"><span class="header-section-number">3.3.1</span> Description</h4>
<p>In <strong>your data</strong> frame, create a new column that returns the weighted average. This new column will feature a weighted average per row of data. <code>X =</code> is specifies that you intend the column to fit into your data frame; <code>MARGIN = 1</code> tells R that we want to calculate values for each row of data present; <code>FUN = function(x)</code> applies the <code>weighted.mean(...)</code> function to each data entry - the range being from the first entry to the last, denoted by <code>nrow(your_data)</code>. For this last part, the <code>x =</code> and <code>y =</code> arguments are called in from the <code>weighted.mean(...)</code> function.</p>
<p><span style="color:red"><strong>Remember, its good practice to have your adjusted weights equal to exactly 1!</strong></span>.</p>
</section>
</div>
</div>
</section>
<section id="the-mode" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="the-mode"><span class="header-section-number">3.4</span> The mode</h3>
<p>Essentially, the mode (<span class="math inline">\(M_o\)</span>) is easily grasped - it tells us the value that occurs most frequently (<span class="math inline">\(f\)</span>), However, its formula can take some time to digest:</p>
<p><span class="math display">\[\begin{equation}
M_o = l + h
\begin{pmatrix}
\frac{f_m - f_1}{2f_m - f_1 - f_2}
\end{pmatrix}
\end{equation}\]</span></p>
<p>Also, here is a vector showing the number of gears in the cars surveyed in the <code>mtcars</code> data set.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>gear</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 4 4 4 3 3 3 3 4 4 4 4 3 3 3 3 3 3 4 4 4 3 3 3 3 3 4 5 5 5 5 5 4</code></pre>
</div>
</div>
<p>In the, <span class="math inline">\(l\)</span> refers to the lower boundary of the modal class. Eyeballing the vector above, we can determine that this value is 3; we can also use the <code>min(...)</code> function to discover this. <span class="math inline">\(h\)</span> refers to the size of the vectors we’re analysing (equivalent to <span class="math inline">\(n\)</span>) - to find this, we can use the <code>length(...)</code> function in R; <span class="math inline">\(f_m\)</span> refers to the frequency corresponding to a modal class (the number of 3s, 4s, and 5s); <span class="math inline">\(f_1\)</span> is the preceding, to a modal class - for 3s this will be 0, for the 4s it will be number of 3s, etc; <span class="math inline">\(f_2\)</span> is the number proceeding to the next modal class - for the 4s this will be the number of 5s.</p>
<p>Solving the formula by hand is a lengthy process, so I won’t stress the details! Instead, it’s worth noting that R does not have a native function for this, you will need to build one from scratch(!); functions will be explained in more detail later in this website. For now let’s try the following based on code shared in <a href="https://www.statology.org/mode-in-r/">Statology</a>:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>calc_mode <span class="ot">&lt;-</span> <span class="cf">function</span>(x) {</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>  u <span class="ot">&lt;-</span> <span class="fu">unique</span>(x)</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>  tab <span class="ot">&lt;-</span> <span class="fu">tabulate</span>(<span class="fu">match</span>(x, u))</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>  u[tab <span class="sc">==</span> <span class="fu">max</span>(tab)]</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>The key thing to note here is that only one piece of information is required here, your vector <code>x</code>. This function uses the <code>unique(...)</code> function that detects unique values and ignores duplications; <code>tabulate(...)</code> calculates the number of times a value appears against a unique entry - this is helped by the <code>match(...)</code> function. The returned result, is the maximum value (note the <code>max(...)</code> function) is the most frequently occurring value detected in the tabulation process.</p>
<p>When the function is applied to the <code>mtcars$gear</code> vector, the result is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc_mode</span>(mtcars<span class="sc">$</span>gear)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>The importance of the mode is important for the next section as it can help to detect <em>centrality</em>.</p>
</section>
</section>
<section id="visual-summaries" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="visual-summaries"><span class="header-section-number">4</span> Visual summaries</h2>
<p>Using functions in R to calculate maximum, minimums, modes and means is useful in getting a ready to present statistics. However, there are times where examining the distribution of your data is advantageous. This can be achieved using three fundamental visualisations (charts):</p>
<ul>
<li>Histogram</li>
<li>Box-Whisker Plot</li>
<li>Q-Q plots</li>
</ul>
<section id="creating-a-histogram-in-r" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="creating-a-histogram-in-r"><span class="header-section-number">4.1</span> Creating a Histogram in R</h3>
<p>A histogram works in a similar way to the mode, but doesn’t go as far as to give a result concerning the most frequently occurring number. It sorts data into ‘bins’.</p>
<style>
.parallax {
  /* The image used */
  background-image: url("Round_and_Metal_Containers.jpg");

  /* Set a specific height */
  min-height: 250px;

  /* Create the parallax scrolling effect */
  background-attachment: fixed;
  background-position: center;
  background-repeat: no-repeat;
  background-size: cover;
}
</style>
<div class="parallax">

</div>
<p>Using the <code>mtcars</code> data set, we can organise the <code>disp</code> variable (engine displacement - cylinder volume) into 3 manually defined bins. The data is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>mtcars<span class="sc">$</span>disp</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 160.0 160.0 108.0 258.0 360.0 225.0 360.0 146.7 140.8 167.6 167.6 275.8
[13] 275.8 275.8 472.0 460.0 440.0  78.7  75.7  71.1 120.1 318.0 304.0 350.0
[25] 400.0  79.0 120.3  95.1 351.0 145.0 301.0 121.0</code></pre>
</div>
</div>
<section id="bins" class="level4" data-number="4.1.1">
<h4 data-number="4.1.1" class="anchored" data-anchor-id="bins"><span class="header-section-number">4.1.1</span> Bins</h4>
<p>The bins are based on approximately equal breaks that are determined using R’s <code>cut(...)</code> function. A little leeway is given to the lowest value (rouding down to 70). The process of calculating the bins in R is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(mtcars<span class="sc">$</span>disp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1]  71.1 472.0</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>bin <span class="ot">&lt;-</span> <span class="fu">cut</span>(mtcars<span class="sc">$</span>disp, <span class="dv">3</span>, <span class="at">dig.lab =</span> <span class="dv">5</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unique</span>(bin)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] (70.699,204.73] (204.73,338.37] (338.37,472.4] 
Levels: (70.699,204.73] (204.73,338.37] (338.37,472.4]</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>bin_2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">204</span>, <span class="dv">338</span>)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(<span class="fu">cut</span>(mtcars<span class="sc">$</span>disp,<span class="fu">c</span>(bin_2,<span class="cn">Inf</span>), <span class="at">dig.lab =</span> <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
 (70,204] (204,338] (338,Inf] 
       16         8         8 </code></pre>
</div>
</div>
</section>
<section id="base-plotting" class="level4" data-number="4.1.2">
<h4 data-number="4.1.2" class="anchored" data-anchor-id="base-plotting"><span class="header-section-number">4.1.2</span> Base plotting</h4>
<p>This data can be easily presented as a histogram using R’s <code>hist(...)</code> function. The <code>prob = FALSE</code> argument ensures that we are only examining frequencies (and not probabilistic density - discussed shortly). Other arugments include:</p>
<ul>
<li><code>labels</code>. When set to <code>TRUE</code>, this argument generates a numerical value that floats above the bars (representing the bin values). These have been included for illustrative purposes and are not always needed in most situations.</li>
<li><code>ylim</code>. This argument sets the limit for the plot’s y-axis. Here, it has been extended so that the labels are clearly visible.</li>
<li><code>xlab</code>. This argument allows you to override the default x-axis text with something more suitable.</li>
<li><code>main</code>. This argument allows you to change the title of the plot. As this is a string value, it is encased in quotation marks.</li>
<li><code>col</code>. This argument sets the colour of the plot. This can be a value from R’s default colour palettes or given as a hex value. See <a href="https://www.nceas.ucsb.edu/sites/default/files/2020-04/colorPaletteCheatsheet.pdf">this cheatsheet</a> for more information.</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="at">x =</span> mtcars<span class="sc">$</span>disp, <span class="at">breaks =</span> <span class="fu">c</span>(<span class="dv">70</span>, <span class="dv">204</span>, <span class="dv">338</span>, <span class="dv">500</span>),</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="cn">TRUE</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="cn">FALSE</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Displacement (cu.in.)"</span>,</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram Example 1"</span>,</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"palegreen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Descriptive_Statistics_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>A histogram can be defined by the number of bins it possess. In a base plot, this is done using <code>n =</code>:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="at">x =</span> mtcars<span class="sc">$</span>disp, <span class="at">breaks =</span> <span class="dv">2</span>,</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="cn">TRUE</span>,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">prob =</span> <span class="cn">FALSE</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>,<span class="dv">20</span>),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Displacement (cu.in.)"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histogram Example 1"</span>,</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"palegreen"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<p><img src="Descriptive_Statistics_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>
</section>
<section id="box-and-whisker-plots" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="box-and-whisker-plots"><span class="header-section-number">5</span> Box-and-whisker plots</h2>
<p>According to Tukey, a Box-and-whisker plot is “a box from hinge to hinge, bared at the median, with”whiskers” to (a) extremes (b) the innermost identified values (c) the adjacent values” <span class="citation" data-cites="tukey1977exploratory">(<a href="#ref-tukey1977exploratory" role="doc-biblioref">1977</a>)</span>. A hinge is defined as <span class="math inline">\(\frac{1}{2}(1+m)\)</span>, where <span class="math inline">\(m\)</span> indicates the depth of the median - it is a quartile. Remember, when applied to a variable, the <code>summary(...)</code> function returns the first and third quartile values:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mtcars<span class="sc">$</span>disp)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   71.1   120.8   196.3   230.7   326.0   472.0 </code></pre>
</div>
</div>
<p>Box-and-whisker plots are commonly referred to as <strong>box plots</strong> and can be considered a visual representation of R’s <code>summary(...)</code> output; from the example showing in <a href="#fig-3">Figure&nbsp;1</a>, at the expense of precision, it can be determined that the median of the data is approximately 196 and that the majority of observations have engine displacements between approximately 121 and slightly above 321 cubic inches.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-3" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-3-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;1: An example of a single box plot (created using <code>ggplot2</code>)</figcaption>
</figure>
</div>
</div>
</div>
<p>In R, this is easily invoked using the <code>boxplot(...)</code> function on the same displacement data featured above (see <a href="#fig-4">Figure&nbsp;2</a>). Again, additional arguments are applied to enhance the aesthetics of the plot:</p>
<ul>
<li><code>col.main</code> allows for the colour of the title to be changed.</li>
<li><code>xaxt</code> switches off the x-axis</li>
</ul>
<p>Furthermore, a new function is introduced, <code>axis(...)</code>. This function reintroduces the x-axis but with customisable number of ticks. An explanation of its arguments is as follows:</p>
<ul>
<li><code>side</code> specifies the axis that we want to alter. 1 refers to the x-axis, while 2 refers to the y-axis. In this plot, the x-axis is where changes are being made</li>
<li><code>at</code> specifies where we want to draw our ticks. Here, I have concatenated a sequence of ticks every 50 units between a range of 0 and 600 using the <code>seq(...)</code> function within.</li>
<li><code>las</code> alters the orientation of the axis text. Here, 2 is used to orientate the text so that it is perpendicular to the axis. A value of 1, forces a horizontal orientation, and 3 forces a vertical orientation. 0 is the default orientation - parallel to the axis.</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">x =</span> mtcars<span class="sc">$</span>disp, <span class="at">horizontal =</span> T, <span class="at">col =</span> <span class="st">"palegreen"</span>,</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">main =</span> <span class="st">"Engine Displacement (cu.in.)"</span>,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">col.main =</span> <span class="st">"red"</span>,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">"n"</span>)</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">600</span>,<span class="dv">50</span>)), <span class="at">las =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-4" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-4-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;2: box plot created using base R</figcaption>
</figure>
</div>
</div>
</div>
<section id="multiple-box-plots" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="multiple-box-plots"><span class="header-section-number">5.1</span> Multiple box-plots</h3>
<p>Observing a single box plot yields a significant amount of information. However, its application becomes significantly richer when examining grouped (banded) data.</p>
<p><a href="#fig-5">Figure&nbsp;3</a> shows engine displacement against the number of gears from the mtcars data set featured so far. To achieve this effect the arugment <code>formula =</code> is used instead of <code>x =</code>; subsequently, a formulaic expression is used <em>y ~ x</em> - <em>disp</em> is actually the y-axis and <em>gear</em>, the x-axis. The order is flipped when <code>horizontal = TRUE</code> is evoked.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(<span class="at">formula =</span> disp <span class="sc">~</span> gear, <span class="at">data =</span> mtcars, <span class="at">horizontal =</span> <span class="cn">TRUE</span>,</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">xaxt =</span> <span class="st">"n"</span>,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">xlab =</span> <span class="st">"Displacement (cu.in.)"</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Number of gears"</span>,</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="st">"palegreen"</span>)</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="at">side =</span> <span class="dv">1</span>, <span class="at">at =</span> <span class="fu">c</span>(<span class="fu">seq</span>(<span class="dv">0</span>,<span class="dv">600</span>,<span class="dv">50</span>)), <span class="at">las =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-5" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-5-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;3: Multiple box-whisker plots</figcaption>
</figure>
</div>
</div>
</div>
<p>From this chart the assertion can be made that a portion of cars with 4 or 5 gear transmissions have similar displacements, particularly at smaller volumes of around 150 cubic inches or less - the middle 50% (interquartile ranges) of the observations intersect.</p>
<p>The left-whisker of the 3 gear transmission cars, indicates that there are observations that fall below the interquartile range, within 1.5 multiplications - there are number of cars with 3 gears that share the upper end of 4-gear transmission cars. However, the bulk of its engine displacement records are shared with 5-gear transmission cars. Comparatively, 3-gear transmission cars have higher engine displacement.</p>
<p>Comparing groups of observations is covered in more detail and with more precision in the ‘inferential statistics’ part of this website.</p>
</section>
</section>
<section id="other-useful-visualisations" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="other-useful-visualisations"><span class="header-section-number">6</span> Other useful visualisations</h2>
<p>During your previous studies you may have come across pie charts, bar plots, and scatters. These plots are useful in aiding in the description of statistics can be built in R.</p>
<section id="pie-charts" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="pie-charts"><span class="header-section-number">6.1</span> Pie charts</h3>
<p>Pie charts came about towards the end of 18th century. They show proportions of observations and may be accompanied with annotations such as percentages or counts, and may include a legend.</p>
<section id="data-preparation" class="level4" data-number="6.1.1">
<h4 data-number="6.1.1" class="anchored" data-anchor-id="data-preparation"><span class="header-section-number">6.1.1</span> Data preparation</h4>
<p>To construct a pie chart in R, you’ll need to supply discrete values. Here, we can use the <code>aggregate(...)</code> function in R to calculate the total number of observations for a predetermined category. Let’s consider the number of gears for straight-engine cars from the <code>mtcars</code> data set. and present is as a frequency table.</p>
<p>The dimensions of the frequency table are defined by a <em>formula</em> that follows an understanding that <span class="math inline">\(y = f(x)\)</span>. In other words, changes along the y-axis are determined by changes along the x-axis; <span class="math inline">\(y\)</span> is dependent on <span class="math inline">\(x\)</span> - this is the premise of linear regression that features later in this manual. Our premise is that shape of the engine determines the number of gears in a car. Therefore, <span class="math inline">\(y\)</span> is the <em>vs</em> variable, while <em>x</em> is the number of gears. As we’re interested in the maximum number of gears the <code>FUN =</code> argument is set to the R function <code>sum</code> (without parentheses). The code is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>freq_data <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="at">x =</span> vs<span class="sc">~</span>gear, <span class="at">data =</span> mtcars, <span class="at">FUN =</span> sum)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>As we are keen to work out the proportion as a percentage, we create a new column in the data frame. The easiest way to this is to add a dollar sign (<code>$</code>) after the name of the data frame and follow this with an appropriate column name i.e.&nbsp;<code>data$name</code>. To calculate a percentage the formula is <span class="math inline">\(\frac{x}{\sum{x}} \times 100\)</span>; a discrete value divided by the row total and then multiplied by 100.</p>
<p>This process produces a continuous value with number of decimal places (d.p.). To control for this, the <code>round(...)</code> function may be used. In principle, this function is <code>round(x, digits = n)</code> - to round 12.18 to 1 d.p., the function will be as follows <code>round(x = 12.18, digits = 1)</code>.</p>
<p>The process of producing a column in our data where a percentage is calculated to 1 d.p. is as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>freq_data<span class="sc">$</span>pct <span class="ot">&lt;-</span> <span class="fu">round</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs<span class="sc">/</span><span class="fu">sum</span>(freq_data<span class="sc">$</span>vs)<span class="sc">*</span><span class="dv">100</span>,<span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="generating-the-graphic" class="level4" data-number="6.1.2">
<h4 data-number="6.1.2" class="anchored" data-anchor-id="generating-the-graphic"><span class="header-section-number">6.1.2</span> Generating the graphic</h4>
<p>Constructing a pie chart in R is achieved using the <code>pie(...)</code> function. The function can be as simple as that used to generate <a href="#fig-6">Figure&nbsp;4</a>.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-6" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-6-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;4: A simple pie chart</figcaption>
</figure>
</div>
</div>
</div>
<p>However, this output doesn’t tell us to too much beyond the proportionality of <em>something</em>. To address this, we can augment the function with labels based on the percentages we’ve already worked out:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs, <span class="at">labels =</span> freq_data<span class="sc">$</span>pct)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-7" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-7-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;5: A simple pie chart with proportional labels</figcaption>
</figure>
</div>
</div>
</div>
<p>While this graphic is fine, it will be better to have actual percentage signs shown. This can be achieved by using the <code>paste(...)</code> function within the <code>labels =</code> argument. This function allows for the insertion of additional text of characters to help enrich an output. For example:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>random_value <span class="ot">=</span> <span class="fl">12.6</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(random_value)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12.6</code></pre>
</div>
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># To add a % sign...</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(random_value,<span class="st">"%"</span>, <span class="st">""</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "12.6 % "</code></pre>
</div>
</div>
<p>There is a space between the number and the percentage sign. To remove this, you can use the <code>sep = ""</code> argument within the <code>paste(...)</code> function.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">paste</span>(random_value, <span class="st">"%"</span>, <span class="at">sep =</span> <span class="st">""</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "12.6%"</code></pre>
</div>
</div>
<p>Applied to our data:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs, <span class="at">labels =</span> <span class="fu">paste</span>(freq_data<span class="sc">$</span>pct,<span class="st">"%"</span>,<span class="at">sep =</span> <span class="st">""</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-8" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-8-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;6: A simple pie chart with clearly annotated proportions</figcaption>
</figure>
</div>
</div>
</div>
<p>Final steps concern aesthetics. If you wanted to specify the colouts yourself, you can do this by creating a new vector that contains the colour codes that you are interested in. For example: <code>custom_col &lt;- c("salmon","seagreen","palegreen")</code>. When plotting your pie chart, you can activate this palette by using the <code>col =</code> argument (see <a href="#fig-9">Figure&nbsp;7</a>)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>custom_col <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"salmon"</span>,<span class="st">"seagreen"</span>,<span class="st">"palegreen"</span>)</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs, <span class="at">labels =</span> <span class="fu">paste</span>(freq_data<span class="sc">$</span>pct,<span class="st">"%"</span>,<span class="at">sep =</span> <span class="st">""</span>), <span class="at">col =</span> custom_col)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-9" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-9-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;7: A pie chart with proportions and customised colour palette</figcaption>
</figure>
</div>
</div>
</div>
<p>As we have no idea of telling what the colours relate to (in terms of car gears), we add a legend based on the number of gears. This is achieved using the <code>legend(...)</code> function on a new line of code. This line of code is dependent on a plot being produced beforehand and cannot be run in isolation. The <code>x =</code> argument in the function specifies the position of the legend, while the <code>legend =</code> argument specifies the labs for your legend; <code>fill =</code> will be the same colour palette used in the pie chart, and <code>title =</code> is the title for your legend. For example:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>custom_col <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"salmon"</span>,<span class="st">"seagreen"</span>,<span class="st">"palegreen"</span>)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a><span class="fu">pie</span>(<span class="at">x =</span> freq_data<span class="sc">$</span>vs, <span class="at">labels =</span> <span class="fu">paste</span>(freq_data<span class="sc">$</span>pct,<span class="st">"%"</span>,<span class="at">sep =</span> <span class="st">""</span>),</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>    <span class="at">col =</span> custom_col)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">"topleft"</span>, <span class="at">legend =</span> <span class="fu">c</span>(freq_data<span class="sc">$</span>gear), <span class="at">fill =</span> custom_col, <span class="at">title =</span> <span class="st">"No. gears"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-10" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-10-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;8: A final render of a pie chart (including legend)</figcaption>
</figure>
</div>
</div>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>When using a custom colour scale with discrete values, ensure that you have the name number of colours as discrete values.</p>
</div>
</div>
</section>
</section>
<section id="bar-plots" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="bar-plots"><span class="header-section-number">6.2</span> Bar plots</h3>
<p>Bar plots (or bar graphs) are visual representations of discrete data frequencies; its height is relative to the number of times a value appears in a vector/variable <span class="citation" data-cites="harris2014statistics">(see <a href="#ref-harris2014statistics" role="doc-biblioref">Harris and Jarvis 2014</a>)</span>.</p>
<p>Creating bar plots in R works in a similar way to the pie chart. Here, the <code>barplot(...)</code> function is used to produce the base graphic, where <code>height =</code> indicates the variable that determines the height of the bars - in the example shown in <a href="#fig-7">Figure&nbsp;5</a>, the variable (vs) is equal to 1, representing the number of straight engine cars.</p>
<p>A simple <code>barplot(...)</code> for our data will be as follows:</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="at">height =</span> freq_data<span class="sc">$</span>vs)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-11" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-11-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;9: A bar plot</figcaption>
</figure>
</div>
</div>
</div>
<p>To furnish this with details, you can use the <code>col =</code> argument to introduce a customised colour scale, use the <code>names.arg =</code> to name the respective columns, and use the <code>las = 2</code> argument to flip the orientation of the labels. Defining the barplot as an object called <strong>bp</strong> returns both the object and plot.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(<span class="at">height =</span> freq_data<span class="sc">$</span>vs, <span class="at">col =</span> custom_col, <span class="at">names.arg =</span> <span class="fu">paste</span>(<span class="st">"Gears:"</span>,freq_data<span class="sc">$</span>gear), <span class="at">las =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-12" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-12-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;10: A labelled bar plot</figcaption>
</figure>
</div>
</div>
</div>
<p>The <strong>bp</strong> object can be used in the <code>text(...)</code> function to create labels that float above the bars. Here, we want the text to be <strong>bp</strong> values, and the labels to be located at at a good distance above the maximum height of each bar (0.5 units).</p>
<p>Again, the <code>legend</code> function is used to produce a legend. This time, it is located to the <em>top-right</em> of the plot space.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>bp <span class="ot">&lt;-</span> <span class="fu">barplot</span>(<span class="at">height =</span> freq_data<span class="sc">$</span>vs, <span class="at">col =</span> custom_col, <span class="at">names.arg =</span> <span class="fu">paste</span>(<span class="st">"Gears:"</span>,freq_data<span class="sc">$</span>gear), <span class="at">las =</span> <span class="dv">2</span>, <span class="at">ylim =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fu">max</span>(freq_data<span class="sc">$</span>vs <span class="sc">+</span> <span class="dv">1</span>)))</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="at">x =</span> bp, <span class="at">y =</span> freq_data<span class="sc">$</span>vs <span class="sc">+</span> <span class="fl">0.5</span>, <span class="at">labels =</span> freq_data<span class="sc">$</span>vs)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="at">x =</span> <span class="st">"topright"</span>, <span class="at">legend =</span> <span class="fu">c</span>(freq_data<span class="sc">$</span>vs), <span class="at">fill =</span> custom_col, <span class="at">title =</span> <span class="st">"No. Straight Engines"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output-display">
<div id="fig-13" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="Descriptive_Statistics_files/figure-html/fig-13-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Figure&nbsp;11: A bar plot with labels and legend</figcaption>
</figure>
</div>
</div>
</div>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-harris2014statistics" class="csl-entry" role="listitem">
Harris, Richard, and Claire Jarvis. 2014. <em>Statistics for Geography and Environmental Science</em>. Routledge.
</div>
<div id="ref-tukey1977exploratory" class="csl-entry" role="listitem">
Tukey, JW. 1977. <span>“Exploratory Data Analysis. Addison-Wesley, Reading, MA.”</span> <em>Exploratory Data Analysis. Addison-Wesley, Reading, MA.</em>
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>
